version: "3"

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  cliapp:
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile.cliapp
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis      
  webapp:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.webapp
    ports:
      - 8080:80
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
